<a href="https://colab.research.google.com/github/Xander50/C-124/blob/main/C_124.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
A=[5,1,2,9,21]
print(A)


[5, 1, 2, 9, 21]


In [3]:
B=[[2,9,6],[4,3,8],[7,5,1]]
print(B)

[[2, 9, 6], [4, 3, 8], [7, 5, 1]]


In [5]:
import numpy as np
arr=np.array([3,0,4,6,1])
print(arr)
print(type(arr))

[3 0 4 6 1]
<class 'numpy.ndarray'>


In [8]:
arr2=np.array([[3,5,1],[0,6,2],[1,4,8]])
print(arr2)
print(type(arr2))

numpy.ndarray

In [9]:
arr3=np.array([[3,5,1],['Alexander',15,True],[1,4,8]])
print(arr3)
print(type(arr3))

[['3' '5' '1']
 ['Alexander' '15' 'True']
 ['1' '4' '8']]
<class 'numpy.ndarray'>


In [11]:
print(A)
print(B)
print(A[3])

[5, 1, 2, 9, 21]
[[2, 9, 6], [4, 3, 8], [7, 5, 1]]
9


In [12]:
print(arr3[1])

['Alexander' '15' 'True']


In [13]:
print(arr3[1][0])

Alexander


In [17]:
print(arr2)
print("___________")
arr2[1,0]=7
print(arr2)
print("#########")
arr2[2,2]=0
print(arr2)

[[3 5 1]
 [7 7 2]
 [1 4 8]]
___________
[[3 5 1]
 [7 7 2]
 [1 4 8]]
#########
[[3 5 1]
 [7 7 2]
 [1 4 0]]


In [19]:
a=np.array([[2,7],[9,5]])
b=np.array([[6,1],[5,3]])
rows=2
cols=2
c=[[0,0],[0,0]]
for i in range(rows):
  for j in range(cols):
    c[i][j]=a[i][j]+b[i][j]
print(a,"\n")
print(b,"\n")
print(c,"\n")

[[2 7]
 [9 5]] 

[[6 1]
 [5 3]] 

[[8, 8], [14, 8]] 



In [20]:
a=np.array([[2,7],[9,5]])
b=np.array([[6,1],[5,3]])
rows=2
cols=2
c=[[0,0],[0,0]]
for i in range(rows):
  for j in range(cols):
    c[i][j]=a[i][j]-b[i][j]
print(a,"\n")
print(b,"\n")
print(c,"\n")

[[2 7]
 [9 5]] 

[[6 1]
 [5 3]] 

[[-4, 6], [4, 2]] 



In [21]:
a=np.array([[2,7],[9,5]])
b=np.array([[6,1],[5,3]])
rows=2
cols=2
c=[[0,0],[0,0]]
for i in range(rows):
  for j in range(cols):
    c[i][j]=a[i][j]*b[i][j]
print(a,"\n")
print(b,"\n")
print(c,"\n")

[[2 7]
 [9 5]] 

[[6 1]
 [5 3]] 

[[12, 7], [45, 15]] 



In [23]:
b1=np.array([[6,1],[5,3],[4,0]])
n=5
mul=np.zeros([3,2])
for i in range(3):
  for j in range(1):
    mul[i][j]=n*b1[i][j]
    print(mul[i][j])
for rows in mul:
  print(rows)

30.0
25.0
20.0
[30.  0.]
[25.  0.]
[20.  0.]


In [24]:
n=5
a1=np.array([2,6,0])
a2=np.multiply(a1,n)
print(a2)

[10 30  0]
